import 'dart:convert';

String getDummyPosTxnHistoryReport(
    {required int pageNumber, required int pageSize}) {
  return jsonEncode({
    "content": [
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
    ],
    "pageable": {
      "sort": {"unsorted": false, "sorted": true, "empty": false},
      "pageSize": pageSize,
      "pageNumber": pageNumber,
      "offset": 40,
      "paged": true,
      "unpaged": false
    },
    "last": false,
    "totalPages": (132 / pageSize).ceil(),
    "totalElements": 132,
    "sort": {"unsorted": false, "sorted": true, "empty": false},
    "first": false,
    "numberOfElements": pageSize,
    "size": pageSize,
    "number": pageNumber,
    "empty": false
  });
}

String getDummyDailySettlementTxnSummary() {
  return jsonEncode({
    "errorMessage": null,
    "successMessage": "Success",
    "statusCode": 200,
    "data": null,
    "map": null,
    "pageData": null,
    "responseData": {
      "txnCount": 60,
      "txnAmount": 50000.0,
      "deductionAmount": 45874.0,
      "pendingSettlementAmount": 6598.0
    }
  });
}

getDummySettlementDashBoardReport() {
  return jsonEncode({
    "settledSummaryPage": null,
    "settlementAggregates": [
      {
        "tranDate": "2025-03-14",
        "totalAmount": 2464.60,
        "transactionCount": 1,
        "utr": "AXISP00615121732"
      },
      {
        "tranDate": "2025-03-13",
        "totalAmount": 494.99,
        "transactionCount": 1,
        "utr": ""
      },
      {
        "tranDate": "2025-03-12",
        "totalAmount": 6683.45,
        "transactionCount": 6,
        "utr": ""
      }
    ],
    "settlementTotal": {
      "totalAmount": 9643.04,
      "transactionCount": 8,
      "settlementCount": 3
    }
  });
}

getDummySettlementHistoryReport() {
  return jsonEncode({
    "settledSummaryPage": {
      "content": [
        {
          "rrn": "000018595864",
          "approveCode": "000048",
          "tranDate": "2025-03-13",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000048",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 494.99,
          "gst": 0.00,
          "mdrAmount": 5.01,
          "grossTransactionAmount": 500.00,
          "reconciled": true
        },
        {
          "rrn": "000018595863",
          "approveCode": "000055",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000055",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 1482.00,
          "gst": 0.00,
          "mdrAmount": 18.00,
          "grossTransactionAmount": 1500.00,
          "reconciled": true
        },
        {
          "rrn": "000018595862",
          "approveCode": "000054",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000054",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 1976.00,
          "gst": 0.00,
          "mdrAmount": 24.00,
          "grossTransactionAmount": 2000.00,
          "reconciled": true
        },
        {
          "rrn": "000018595861",
          "approveCode": "000053",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000053",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 1990.00,
          "gst": 0.00,
          "mdrAmount": 10.00,
          "grossTransactionAmount": 2000.00,
          "reconciled": true
        },
        {
          "rrn": "000018595860",
          "approveCode": "000052",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000052",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 488.75,
          "gst": 0.00,
          "mdrAmount": 11.25,
          "grossTransactionAmount": 500.00,
          "reconciled": true
        },
        {
          "rrn": "000018595859",
          "approveCode": "000051",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000051",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 48.50,
          "gst": 0.00,
          "mdrAmount": 1.50,
          "grossTransactionAmount": 50.00,
          "reconciled": true
        },
        {
          "rrn": "000018595858",
          "approveCode": "000050",
          "tranDate": "2025-03-12",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000050",
          "mid": "651076000006945",
          "utr": "",
          "totalAmountPayable": 698.20,
          "gst": 0.00,
          "mdrAmount": 2.80,
          "grossTransactionAmount": 701.00,
          "reconciled": true
        },
        {
          "rrn": "000018595857",
          "approveCode": "000049",
          "tranDate": "2025-03-14",
          "merPayDone": true,
          "misDone": true,
          "merchantTxnIdAuthId": "000049",
          "mid": "651076000006945",
          "utr": "AXISP00615121732",
          "totalAmountPayable": 2464.60,
          "gst": 0.00,
          "mdrAmount": 35.40,
          "grossTransactionAmount": 2500.00,
          "reconciled": true
        }
      ],
      "pageable": {
        "sort": {"unsorted": false, "sorted": true, "empty": false},
        "pageSize": 30,
        "pageNumber": 0,
        "offset": 0,
        "paged": true,
        "unpaged": false
      },
      "last": true,
      "totalPages": 1,
      "totalElements": 8,
      "sort": {"unsorted": false, "sorted": true, "empty": false},
      "first": true,
      "numberOfElements": 8,
      "size": 30,
      "number": 0,
      "empty": false
    },
    "settlementAggregates": [
      {
        "tranDate": "2025-03-14",
        "totalAmount": 2464.60,
        "transactionCount": 1,
        "utr": "AXISP00615121732"
      },
      {
        "tranDate": "2025-03-13",
        "totalAmount": 494.99,
        "transactionCount": 1,
        "utr": ""
      },
      {
        "tranDate": "2025-03-12",
        "totalAmount": 6683.45,
        "transactionCount": 6,
        "utr": ""
      }
    ],
    "settlementTotal": {
      "totalAmount": 9643.04,
      "transactionCount": 8,
      "settlementCount": 3
    }
  });
}
