import 'dart:convert';

String getDummyPosTxnHistoryReport(
    {required int pageNumber, required int pageSize}) {
  return jsonEncode({
    "content": [
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
      {
        "merchantId": "65OMA0000000002",
        "acquirerId": "OMAIND",
        "terminalId": "OM000002",
        "transactionDate": "22/08/2024",
        "transactionTime": "15:05:08",
        "stan": "000023",
        "rrn": "000017088748",
        "amount": "50.00",
        "authCode": "050755",
        "responseCode": "00",
        "responseDesc": null,
        "transactionType": "OSAL001",
        "mcc": null,
        "cardNo": "679999*********4324",
        "merReceiptLink": null,
        "custReceiptLink": null,
        "acquirerName": null,
        "mti": "1210",
        "currency": "356",
        "terminalGuid": 0,
        "txnGuid": 0,
        "insertDateTime": "22/08/2024 15:05:09",
        "isReverse": false,
        "batchNo": "001",
        "traceNumber": "000023",
        "terminalLocation": "TEST MERCHANT         SHARJAH      SHJAE",
        "de_7": "0822110506",
        "acquiringBIN": "OMAIND",
        "schemeName": null,
        "processCode": "000000",
        "p2pRequestId": null,
        "posEntryMode": "071",
        "deviceType": null,
        "txnSource": null,
        "nameOnCard": null,
        "batchClosedOn": null,
        "settledOn": null,
        "processAck": false,
        "txnResponse": null,
        "txnAckResponse": null,
        "batchClosed": false,
        "settled": false,
        "voided": false
      },
    ],
    "pageable": {
      "sort": {"unsorted": false, "sorted": true, "empty": false},
      "pageSize": pageSize,
      "pageNumber": pageNumber,
      "offset": 40,
      "paged": true,
      "unpaged": false
    },
    "last": false,
    "totalPages": (132 / pageSize).ceil(),
    "totalElements": 132,
    "sort": {"unsorted": false, "sorted": true, "empty": false},
    "first": false,
    "numberOfElements": pageSize,
    "size": pageSize,
    "number": pageNumber,
    "empty": false
  });
}
