name: sifr_latest
description: SIFR Payment Project.
publish_to: 'none'
version: 1.0.12+7
versionCode: 7

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  accordion:
  adaptive_dialog:
  awesome_card:
  awesome_snackbar_content:
  badges:
  cached_network_image:
  connectivity_plus:
  credit_card_scanner:
  credit_card_validator:
  cupertino_icons:
  custom_info_window:
  custom_timer:
  dropdown_search:
  flutter_custom_carousel_slider:
  flutter_html_to_pdf:
  flutter_image_compress:
  # flutter_launcher_icons: ^0.13.1
  flutter_localization:
  flutter_otp_text_field:
  flutter_pin_code_widget:
  flutter_swipe_button:
  flutter_toggle_tab:
  geocoding:
  geolocator:
  get_it:
  google_fonts:
  google_maps_flutter:
  grouped_list:
  hive_flutter:
  http:
  icons_plus:
  image_cropper:
  image_picker:
  intl:
  intl_phone_field:
  loading_animation_widget:
  local_auth:
  location:
  lottie:
  majascan: ^0.5.0
  marquee:
  open_file_plus:
  open_mail_app:
  otp_text_field:
  package_info_plus:
  page_transition:
  path:
  path_provider:
  permission_handler:
  provider:
  qr_flutter:
  secure_application:
  shared_preferences:
  # tbib_splash_screen: ^1.0.0
  timelines:
  url_launcher:
  email_validator:
  firebase_core:
  firebase_messaging:
  cloud_firestore:
  flutter_local_notifications:
  overlay_support:
  aes256gcm:
  easy_splash_screen:
  device_info_plus:
  sms_otp_auto_verify:
  fluttertoast:
  sms_autodetect:
  flutter_shimmer_widget:
  flutter_windowmanager:
  keyboard_actions:
  flutter_jailbreak_detection: ^1.10.0
  encrypt:
  pinput:
  syncfusion_flutter_charts: ^24.1.44+1
  timeline_tile: ^2.0.0
  file_picker: ^6.1.1
  flutter_launcher_icons:
#  modal_bottom_sheet: ^2.1.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/screen/anet.png"

dependency_overrides:
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0


#  modal_bottom_sheet:
#    git:
#      url: https://github.com/danReynolds/modal_bottom_sheet.git
#      path: modal_bottom_sheet


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/bg-pattern/
    - assets/screen/
    - assets/lottie/
    - assets/app/
    - assets/ca/
    - assets/app_icons/
    - assets/merchant_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
          weight: 100
    - family: Mont
      fonts:
        - asset: assets/fonts/Mont-Bold.otf

    - family: Mont-regular
      fonts:
        - asset: assets/fonts/Mont-Regular.otf

