import 'file_downloader_stub.dart'
    if (dart.library.html) 'file_downloader_web.dart'
    if (dart.library.io) 'file_downloader_io.dart' as platform;

/// Saves generated bytes as a download on web, or a local file on mobile.
Future<void> downloadFile({
  required List<int> bytes,
  required String filename,
  String mimeType = 'application/octet-stream',
}) {
  return platform.downloadFile(
    bytes: bytes,
    filename: _safeFilename(filename),
    mimeType: mimeType,
  );
}

String _safeFilename(String value) {
  final cleaned = value
      .replaceAll(RegExp(r'[^A-Za-z0-9._-]'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_+|_+$'), '');

  return cleaned.isEmpty ? 'anet_download' : cleaned;
}
