import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { english, hindi, malayalam, tamil }

class AppLanguageController extends ChangeNotifier {
  static const _languagePreferenceKey = 'language_preference';

  AppLanguage _language = AppLanguage.english;

  AppLanguage get language => _language;

  Locale get locale {
    switch (_language) {
      case AppLanguage.english:
        return const Locale('en');
      case AppLanguage.hindi:
        return const Locale('hi');
      case AppLanguage.malayalam:
        return const Locale('ml');
      case AppLanguage.tamil:
        return const Locale('ta');
    }
  }

  Future<void> loadLanguagePreference() async {
    final preferences = await SharedPreferences.getInstance();
    final savedLanguage = preferences.getString(_languagePreferenceKey);
    _language = _languageFromName(savedLanguage);
  }

  Future<void> setLanguage(AppLanguage language) async {
    if (_language == language) {
      return;
    }

    _language = language;
    notifyListeners();

    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_languagePreferenceKey, language.name);
  }

  Future<void> resetLanguagePreference() async {
    if (_language != AppLanguage.english) {
      _language = AppLanguage.english;
      notifyListeners();
    }

    final preferences = await SharedPreferences.getInstance();
    await preferences.remove(_languagePreferenceKey);
  }

  AppLanguage _languageFromName(String? value) {
    return AppLanguage.values.firstWhere(
      (language) => language.name == value,
      orElse: () => AppLanguage.english,
    );
  }
}

final appLanguageController = AppLanguageController();

class AppLanguageScope extends InheritedNotifier<AppLanguageController> {
  const AppLanguageScope({
    super.key,
    required AppLanguageController controller,
    required super.child,
  }) : super(notifier: controller);

  static AppLanguageController of(BuildContext context) {
    return context
            .dependOnInheritedWidgetOfExactType<AppLanguageScope>()
            ?.notifier ??
        appLanguageController;
  }
}

extension AppLocalization on BuildContext {
  String tr(String key) {
    final language = AppLanguageScope.of(this).language;
    return _localizedValues[language]?[key] ??
        _localizedValues[AppLanguage.english]?[key] ??
        key;
  }
}

String languageLabel(AppLanguage language) {
  switch (language) {
    case AppLanguage.english:
      return 'English';
    case AppLanguage.hindi:
      return 'हिंदी';
    case AppLanguage.malayalam:
      return 'മലയാളം';
    case AppLanguage.tamil:
      return 'தமிழ்';
  }
}

const Map<AppLanguage, Map<String, String>> _localizedValues = {
  AppLanguage.english: {
    'home': 'Home',
    'support': 'Support',
    'dashboard': 'Dashboard',
    'profile': 'Profile',
    'loading': 'Loading...',
    'login_logging_in': 'Logging in...',
    'login_success': 'Login successful!',
    'login_failed': 'Login failed',
    'secure_session_unavailable':
        'Secure session storage is unavailable. Open the app using HTTPS or localhost and try again.',
    'unknown_error': 'Unknown error',
    'login_subtitle': 'Before continue, please sign in first',
    'login_welcome_title': 'Welcome Back!',
    'login_title': 'Merchant Sign In',
    'username_label': 'Username / Email / Terminal ID',
    'username_hint': 'Username',
    'username_required': 'Please enter your username',
    'password_label': 'Password',
    'password_hint': 'Password',
    'password_required': 'Please enter your password',
    'show_password': 'Show password',
    'hide_password': 'Hide password',
    'remember_me': 'Remember me',
    'sign_in': 'Sign In',
    'forgot_password': 'Forgot Password?',
    'or': '--- Or ---',
    'connect_with_us': 'Connect With Us',
    'merchant_name': 'MERCHANT NAME',
    'today_success': 'Total Success transactions today',
    'no_transactions': 'No transactions available',
    'no_vpa_transactions': 'No Vpa transactions available',
    'transactions': 'transactions',
    'page': 'Page',
    'of': 'of',
    'previous_page': 'Previous page',
    'next_page': 'Next page',
    'view_all_transactions': 'View All transactions',
    'view_all_settlements': 'View All Settlements',
    'today_settlements': 'Today Settlements',
    'settled_amount': 'Settled Amount',
    'deductions': 'Deductions',
    'pending_settlements': 'Pending Settlements',
    'total_amount_settled': 'Total Amount Settled',
    'total_settlements': 'Total Settlements',
    'total_transactions': 'Total Transactions',
    'total_amount': 'Total Amount',
    'utr_wise_settlement': 'UTR Wise Settlement',
    'settled_on': 'Settled on',
    'transaction_activity': 'Transaction Activity',
    'settlement_breakdown': 'Settlement Breakdown',
    'tap_deduction_details': 'Tap to view deduction details',
    'hide_deductions': 'Hide Deductions',
    'view_deductions': 'View Deductions',
    'amt_packed_settlement': 'Amt Packed for Settlement',
    'refund_amount': 'Refund Amount',
    'chargeback_amount': 'Chargeback Amount',
    'loan_recovery_amount': 'Loan Recovery Amount',
    'msf_mdr': 'MSF/MDR',
    'late_stl_fee': 'Late Stl Fee',
    'others': 'Others',
    'pos_txns_history': 'POS Txns History',
    'qr_txns_history': 'QR Txns History',
    'settlements': 'Settlements',
    'recent_transactions': 'Recent transactions',
    'dashboard_title': 'Dashboard',
    'dashboard_message': 'Dashboard details will be shown here.',
    'basic_info': 'Basic Info',
    'shop_name': 'Shop Name',
    'merchant_id': 'Merchant ID',
    'role': 'Role',
    'device_type': 'Device Type',
    'not_available': 'Not available',
    'no_email': 'No email available',
    'merchant_user': 'Merchant User',
    'app_settings': 'App Settings',
    'app_language': 'App Language',
    'theme': 'Theme',
    'color_combination': 'Color Combination',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'about_app': 'About App',
    'app_name': 'App Name',
    'description': 'Description',
    'app_description': 'Merchant payments and support app',
    'quick_actions': 'Quick Actions',
    'loading_options': 'Loading options...',
    'select_option': 'Select an option',
    'help_desk': 'HELP\nDESK',
    'here_to_help': 'We are here to help!',
    'raise_concern': 'Raise Your Concern and\nget your issue resolved',
    'raising_request': 'Raising request...',
    'raise_request': 'Raise a request',
    'contact_us': 'Contact us:',
    'support_request_success': 'Support request raised successfully',
    'support_request_failed': 'Support request failed',
    'filter_required': 'Filter required',
    'select_date_range': 'Please select a date range',
    'select_vpa': 'Please select a VPA',
    'enter_rrn': 'Please enter RRN',
    'enter_app_code': 'Please enter App Code',
    'select_filter_any':
        'Please select a date range, terminal, RRN, or App Code',
    'ok': 'OK',
    'reset': 'Reset',
    'apply': 'Apply',
    'vpa': 'Vpa',
    'select': 'Select',
    'payment_tid': 'Payment Tid',
    'search_by': 'Search By',
    'date': 'Date',
    'rrn_app_code': 'RRN/App Code',
    'tid_vpa': 'Tid',
    'payment_mode': 'Payment Mode',
    'enter_rrn_hint': 'Enter RRN',
    'enter_app_code_hint': 'Enter App Code',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'last_7_days': 'Last 7 Days',
    'last_1_month': 'Last 1 Month',
    'custom_date_range': 'Custom Date Range',
    'search_result': 'Search result',
    'select_date': 'Select date',
    'cancel': 'Cancel',
    'clear': 'Clear',
    'select_date_range_tooltip': 'Select date range',
    'back': 'Back',
    'notifications': 'Notifications',
    'no_notifications': 'No notifications',
    'no_notifications_message': 'You do not have any notifications right now.',
    'logout': 'Logout',
    'logout_confirm_title': 'Logout?',
    'logout_confirm_message': 'Are you sure you want to logout?',
    'select_language': 'Select Language',
    'change_language': 'Change Language',
    'download': 'Download',
    'send_by_email': 'Send By Email',
    'open_contact_failed': 'Could not open this contact option',
    'amount': 'Amount',
    'refresh': 'Refresh',
    'pos_txns_compact': 'POS\nTxns',
    'qr_txns_compact': 'QR\nTxns',
    'settlements_compact': 'Settle\nments',
    'total_amount_settled_today': 'Total amount settled today',
    'total_deductions_today': 'Total deductions today',
    'total_pending_settlements': 'Total pending settlements',
    'terminals_vpas': 'Terminals & VPAs',
    'terminals': 'Terminals',
    'vpas': 'VPAs',
    'device_application': 'Device & Application',
    'app_version': 'App Version',
    'os_version': 'OS Version',
    'platform': 'Platform',
    'device_model': 'Device Model',
    'check_for_updates': 'Check for Updates',
    'tap_check_app_updates': 'Tap to check app updates',
    'app_up_to_date': 'Your app is up to date.',
    'app_update_message':
        'A new version is available. Please update the application.',
    'update_required': 'Update Required',
    'update_available': 'Update Available',
    'current_version': 'Current version',
    'latest_version': 'Latest version',
    'later': 'Later',
    'update': 'Update',
    'could_not_open_update_link': 'Could not open update link',
    'no_internet_title': 'No Internet Connection',
    'no_internet_message':
        'Please check your connection. The app will resume automatically once internet is restored.',
    'month_vs_transaction_amount': 'Month vs Transaction Amount',
    'from': 'From',
    'to': 'To',
    'forgot_password_title': 'Forgot Password',
    'forgot_password_instruction':
        'Enter your username, email, or terminal ID to request password reset help.',
    'forgot_password_identifier_label': 'Username / Email / Terminal ID',
    'forgot_password_identifier_hint': 'Enter registered details',
    'forgot_password_identifier_required':
        'Please enter username, email, or terminal ID',
    'forgot_password_submit': 'Submit Request',
    'forgot_password_submitted': 'Password reset request submitted',
    'forgot_password_submitted_message':
        'Our support team will help you reset your password.',
    'forgot_password_failed':
        'Could not submit password reset request. Please try again.',
    'otp_sent': 'OTP sent successfully',
    'otp_validation_title': 'OTP Validation',
    'otp_validation_message': 'Enter the OTP sent to your registered contact.',
    'enter_otp': 'Enter OTP',
    'otp_required': 'Please enter OTP',
    'verify_otp': 'Verify OTP',
    'otp_verified': 'OTP verified successfully',
    'otp_validation_failed': 'OTP verification failed',
    'otp_validation_pending': 'OTP validation API is not configured yet.',
    'alert': 'Alert',
    'success': 'Success',
    'error': 'Error',
    'warning': 'Warning',
    'continue': 'Continue',
    'reset_password_required': 'Reset Password Required',
    'reset_password_required_message':
        'Please reset your password to continue.',
    'reset_password_title': 'Reset Password',
    'reset_password_instruction':
        'Create a new password for your merchant account.',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'current_password_required': 'Please enter your current password',
    'new_password_required': 'Please enter a new password',
    'confirm_password_required': 'Please confirm your new password',
    'passwords_do_not_match': 'Passwords do not match',
    'new_password_same_as_current':
        'New password must be different from current password',
    'reset_password_submit': 'Reset Password',
    'reset_password_success': 'Password reset successfully',
    'reset_password_failed': 'Password reset failed. Please try again.',
    'back_to_login': 'Back to Login',
    'secure_your': 'Secure your',
    'merchant_account': 'merchant account',
    'reset_password_hero_message':
        'Reset your password to continue managing your business with ANET.',
    'current_password_hint': 'Enter your current password',
    'new_password_hint': 'Enter your new password',
    'confirm_password_hint': 'Confirm your new password',
    'password_must_contain': 'Password must contain:',
    'password_minimum_characters': 'At least 8 characters',
    'password_uppercase_letter': 'One uppercase letter',
    'password_number': 'One number',
    'password_special_character': 'One special character',
    'resetting_password': 'Resetting password...',
    'sending_email': 'Sending email...',
    'email_report_sent': 'Report request sent to your registered email.',
    'email_report_failed': 'Could not send the email report. Please try again.',
    'no_transactions_to_send': 'No transactions are available to send.',
    'all_merchants': 'All',
  },
  AppLanguage.malayalam: {
    'home': 'ഹോം',
    'support': 'സപ്പോർട്ട്',
    'dashboard': 'ഡാഷ്ബോർഡ്',
    'profile': 'പ്രൊഫൈൽ',
    'loading': 'ലോഡ് ചെയ്യുന്നു...',
    'login_logging_in': 'ലോഗിൻ ചെയ്യുന്നു...',
    'login_success': 'ലോഗിൻ വിജയിച്ചു!',
    'login_failed': 'ലോഗിൻ പരാജയപ്പെട്ടു',
    'secure_session_unavailable':
        'സുരക്ഷിത സെഷൻ സംഭരണം ലഭ്യമല്ല. HTTPS അല്ലെങ്കിൽ localhost ഉപയോഗിച്ച് ആപ്പ് തുറന്ന് വീണ്ടും ശ്രമിക്കുക.',
    'unknown_error': 'അജ്ഞാത പിശക്',
    'login_subtitle': 'തുടരുന്നതിന് മുമ്പ് സൈൻ ഇൻ ചെയ്യുക',
    'login_welcome_title': 'സ്വാഗതം!',
    'login_title': 'മർച്ചന്റ് സൈൻ ഇൻ',
    'username_label': 'ഉപയോക്തൃനാമം / ഇമെയിൽ / ടെർമിനൽ ID',
    'username_hint': 'ഉപയോക്തൃനാമം',
    'username_required': 'ദയവായി ഉപയോക്തൃനാമം നൽകുക',
    'password_label': 'പാസ്‌വേഡ്',
    'password_hint': 'പാസ്‌വേഡ്',
    'password_required': 'ദയവായി പാസ്‌വേഡ് നൽകുക',
    'show_password': 'പാസ്‌വേഡ് കാണിക്കുക',
    'hide_password': 'പാസ്‌വേഡ് മറയ്ക്കുക',
    'remember_me': 'എന്നെ ഓർക്കുക',
    'sign_in': 'സൈൻ ഇൻ',
    'forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
    'or': '--- അല്ലെങ്കിൽ ---',
    'connect_with_us': 'ഞങ്ങളുമായി ബന്ധപ്പെടുക',
    'merchant_name': 'മർച്ചന്റ് പേര്',
    'today_success': 'ഇന്നത്തെ ആകെ വിജയകരമായ ഇടപാടുകൾ',
    'no_transactions': 'ഇടപാടുകളൊന്നുമില്ല',
    'no_vpa_transactions': 'VPA ഇടപാടുകളൊന്നുമില്ല',
    'transactions': 'ഇടപാടുകൾ',
    'page': 'പേജ്',
    'of': 'ൽ',
    'previous_page': 'മുമ്പത്തെ പേജ്',
    'next_page': 'അടുത്ത പേജ്',
    'view_all_transactions': 'എല്ലാ ഇടപാടുകളും കാണുക',
    'view_all_settlements': 'എല്ലാ സെറ്റിൽമെന്റുകളും കാണുക',
    'today_settlements': 'ഇന്നത്തെ സെറ്റിൽമെന്റുകൾ',
    'settled_amount': 'സെറ്റിൽ ചെയ്ത തുക',
    'deductions': 'കിഴിവുകൾ',
    'pending_settlements': 'ബാക്കിയുള്ള സെറ്റിൽമെന്റുകൾ',
    'total_amount_settled': 'ആകെ സെറ്റിൽ ചെയ്ത തുക',
    'total_settlements': 'ആകെ സെറ്റിൽമെന്റുകൾ',
    'total_transactions': 'ആകെ ഇടപാടുകൾ',
    'total_amount': 'ആകെ തുക',
    'utr_wise_settlement': 'UTR അനുസരിച്ചുള്ള സെറ്റിൽമെന്റ്',
    'settled_on': 'സെറ്റിൽ ചെയ്തത്',
    'transaction_activity': 'ഇടപാട് പ്രവർത്തനം',
    'settlement_breakdown': 'സെറ്റിൽമെന്റ് ബ്രേക്ക്‌ഡൗൺ',
    'tap_deduction_details': 'കിഴിവ് വിവരങ്ങൾ കാണാൻ ടാപ്പ് ചെയ്യുക',
    'hide_deductions': 'കിഴിവുകൾ മറയ്ക്കുക',
    'view_deductions': 'കിഴിവുകൾ കാണുക',
    'amt_packed_settlement': 'സെറ്റിൽമെന്റിനുള്ള തുക',
    'refund_amount': 'റിഫണ്ട് തുക',
    'chargeback_amount': 'ചാർജ്‌ബാക്ക് തുക',
    'loan_recovery_amount': 'ലോൺ റിക്കവറി തുക',
    'msf_mdr': 'MSF/MDR',
    'late_stl_fee': 'വൈകിയ സെറ്റിൽമെന്റ് ഫീസ്',
    'others': 'മറ്റുള്ളവ',
    'pos_txns_history': 'POS ഇടപാട് ചരിത്രം',
    'qr_txns_history': 'QR ഇടപാട് ചരിത്രം',
    'settlements': 'സെറ്റിൽമെന്റുകൾ',
    'recent_transactions': 'സമീപകാല ഇടപാടുകൾ',
    'dashboard_title': 'ഡാഷ്ബോർഡ്',
    'dashboard_message': 'ഡാഷ്ബോർഡ് വിവരങ്ങൾ ഇവിടെ കാണിക്കും.',
    'basic_info': 'അടിസ്ഥാന വിവരം',
    'shop_name': 'കടയുടെ പേര്',
    'merchant_id': 'മർച്ചന്റ് ID',
    'role': 'റോൾ',
    'device_type': 'ഉപകരണ തരം',
    'not_available': 'ലഭ്യമല്ല',
    'no_email': 'ഇമെയിൽ ലഭ്യമല്ല',
    'merchant_user': 'മർച്ചന്റ് ഉപയോക്താവ്',
    'app_settings': 'ആപ്പ് ക്രമീകരണങ്ങൾ',
    'app_language': 'ആപ്പ് ഭാഷ',
    'theme': 'തീം',
    'color_combination': 'കളർ കോമ്പിനേഷൻ',
    'system': 'സിസ്റ്റം',
    'light': 'ലൈറ്റ്',
    'dark': 'ഡാർക്ക്',
    'about_app': 'ആപ്പിനെ കുറിച്ച്',
    'app_name': 'ആപ്പ് പേര്',
    'description': 'വിവരണം',
    'app_description': 'മർച്ചന്റ് പേയ്മെന്റുകളും സപ്പോർട്ട് ആപ്പും',
    'quick_actions': 'വേഗത്തിലുള്ള പ്രവർത്തനങ്ങൾ',
    'loading_options': 'ഓപ്ഷനുകൾ ലോഡ് ചെയ്യുന്നു...',
    'select_option': 'ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക',
    'help_desk': 'ഹെൽപ്പ്\nഡെസ്ക്',
    'here_to_help': 'സഹായിക്കാൻ ഞങ്ങൾ ഇവിടെ!',
    'raise_concern': 'നിങ്ങളുടെ പ്രശ്നം അറിയിക്കുക\nപരിഹാരം നേടുക',
    'raising_request': 'അഭ്യർത്ഥന അയയ്ക്കുന്നു...',
    'raise_request': 'അഭ്യർത്ഥന അയയ്ക്കുക',
    'contact_us': 'ബന്ധപ്പെടുക:',
    'support_request_success': 'സപ്പോർട്ട് അഭ്യർത്ഥന വിജയകരമായി അയച്ചു',
    'support_request_failed': 'സപ്പോർട്ട് അഭ്യർത്ഥന പരാജയപ്പെട്ടു',
    'filter_required': 'ഫിൽറ്റർ ആവശ്യമാണ്',
    'select_date_range': 'ദയവായി തീയതി പരിധി തിരഞ്ഞെടുക്കുക',
    'select_vpa': 'ദയവായി VPA തിരഞ്ഞെടുക്കുക',
    'enter_rrn': 'ദയവായി RRN നൽകുക',
    'enter_app_code': 'ദയവായി ആപ്പ് കോഡ് നൽകുക',
    'select_filter_any':
        'തീയതി പരിധി, ടെർമിനൽ, RRN, അല്ലെങ്കിൽ ആപ്പ് കോഡ് തിരഞ്ഞെടുക്കുക',
    'ok': 'ശരി',
    'reset': 'റീസെറ്റ്',
    'apply': 'പ്രയോഗിക്കുക',
    'vpa': 'VPA',
    'select': 'തിരഞ്ഞെടുക്കുക',
    'payment_tid': 'പേയ്മെന്റ് TID',
    'search_by': 'തിരയുക',
    'date': 'തീയതി',
    'rrn_app_code': 'RRN/ആപ്പ് കോഡ്',
    'tid_vpa': 'TID',
    'payment_mode': 'പേയ്മെന്റ് മോഡ്',
    'enter_rrn_hint': 'RRN നൽകുക',
    'enter_app_code_hint': 'ആപ്പ് കോഡ് നൽകുക',
    'today': 'ഇന്ന്',
    'yesterday': 'ഇന്നലെ',
    'last_7_days': 'കഴിഞ്ഞ 7 ദിവസം',
    'last_1_month': 'കഴിഞ്ഞ 1 മാസം',
    'custom_date_range': 'ഇഷ്ടാനുസൃത തീയതി പരിധി',
    'search_result': 'തിരയൽ ഫലം',
    'select_date': 'തീയതി തിരഞ്ഞെടുക്കുക',
    'cancel': 'റദ്ദാക്കുക',
    'clear': 'ക്ലിയർ',
    'select_date_range_tooltip': 'തീയതി പരിധി തിരഞ്ഞെടുക്കുക',
    'back': 'തിരികെ',
    'notifications': 'അറിയിപ്പുകൾ',
    'logout': 'ലോഗ് ഔട്ട്',
    'logout_confirm_title': 'ലോഗ് ഔട്ട് ചെയ്യണോ?',
    'logout_confirm_message': 'നിങ്ങൾക്ക് ലോഗ് ഔട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
    'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'change_language': 'ഭാഷ മാറ്റുക',
    'download': 'ഡൗൺലോഡ്',
    'send_by_email': 'ഇമെയിൽ വഴി അയയ്ക്കുക',
    'open_contact_failed': 'ഈ കോൺടാക്റ്റ് ഓപ്ഷൻ തുറക്കാൻ കഴിഞ്ഞില്ല',
    'amount': 'തുക',
    'refresh': 'പുതുക്കുക',
    'pos_txns_compact': 'POS\nഇടപാട്',
    'qr_txns_compact': 'QR\nഇടപാട്',
    'settlements_compact': 'സെറ്റിൽ\nമെന്റ്',
    'total_amount_settled_today': 'ഇന്ന് സെറ്റിൽ ചെയ്ത ആകെ തുക',
    'total_deductions_today': 'ഇന്നത്തെ ആകെ കിഴിവുകൾ',
    'total_pending_settlements': 'ബാക്കിയുള്ള സെറ്റിൽമെന്റുകൾ',
    'terminals_vpas': 'ടെർമിനലുകളും VPAകളും',
    'terminals': 'ടെർമിനലുകൾ',
    'vpas': 'VPAകൾ',
    'device_application': 'ഉപകരണവും ആപ്പും',
    'app_version': 'ആപ്പ് പതിപ്പ്',
    'os_version': 'OS പതിപ്പ്',
    'platform': 'പ്ലാറ്റ്ഫോം',
    'device_model': 'ഉപകരണ മോഡൽ',
    'check_for_updates': 'അപ്ഡേറ്റുകൾ പരിശോധിക്കുക',
    'tap_check_app_updates': 'ആപ്പ് അപ്ഡേറ്റുകൾ പരിശോധിക്കാൻ ടാപ്പ് ചെയ്യുക',
    'app_up_to_date': 'നിങ്ങളുടെ ആപ്പ് പുതുതാണ്.',
    'app_update_message':
        'പുതിയ പതിപ്പ് ലഭ്യമാണ്. ദയവായി ആപ്പ് അപ്ഡേറ്റ് ചെയ്യുക.',
    'update_required': 'അപ്ഡേറ്റ് നിർബന്ധമാണ്',
    'update_available': 'അപ്ഡേറ്റ് ലഭ്യമാണ്',
    'current_version': 'നിലവിലെ പതിപ്പ്',
    'latest_version': 'പുതിയ പതിപ്പ്',
    'later': 'പിന്നീട്',
    'update': 'അപ്ഡേറ്റ്',
    'could_not_open_update_link': 'അപ്ഡേറ്റ് ലിങ്ക് തുറക്കാൻ കഴിഞ്ഞില്ല',
    'no_internet_title': 'ഇന്റർനെറ്റ് ബന്ധമില്ല',
    'no_internet_message':
        'ദയവായി കണക്ഷൻ പരിശോധിക്കുക. ഇന്റർനെറ്റ് ലഭിക്കുമ്പോൾ ആപ്പ് സ്വയം തുടരും.',
    'month_vs_transaction_amount': 'മാസം vs ഇടപാട് തുക',
    'from': 'മുതൽ',
    'to': 'വരെ',
    'forgot_password_title': 'പാസ്‌വേഡ് മറന്നോ',
    'forgot_password_instruction':
        'പാസ്‌വേഡ് റീസെറ്റ് സഹായത്തിനായി ഉപയോക്തൃനാമം, ഇമെയിൽ അല്ലെങ്കിൽ ടെർമിനൽ ID നൽകുക.',
    'forgot_password_identifier_label': 'ഉപയോക്തൃനാമം / ഇമെയിൽ / ടെർമിനൽ ID',
    'forgot_password_identifier_hint': 'രജിസ്റ്റർ ചെയ്ത വിവരങ്ങൾ നൽകുക',
    'forgot_password_identifier_required':
        'ദയവായി ഉപയോക്തൃനാമം, ഇമെയിൽ അല്ലെങ്കിൽ ടെർമിനൽ ID നൽകുക',
    'forgot_password_submit': 'അഭ്യർത്ഥന സമർപ്പിക്കുക',
    'forgot_password_submitted': 'പാസ്‌വേഡ് റീസെറ്റ് അഭ്യർത്ഥന സമർപ്പിച്ചു',
    'forgot_password_submitted_message':
        'നിങ്ങളുടെ പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യാൻ ഞങ്ങളുടെ പിന്തുണ ടീം സഹായിക്കും.',
    'forgot_password_failed':
        'പാസ്‌വേഡ് റീസെറ്റ് അഭ്യർത്ഥന സമർപ്പിക്കാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    'otp_sent': 'OTP വിജയകരമായി അയച്ചു',
    'otp_validation_title': 'OTP പരിശോധന',
    'otp_validation_message':
        'നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത കോൺടാക്റ്റിലേക്ക് അയച്ച OTP നൽകുക.',
    'enter_otp': 'OTP നൽകുക',
    'otp_required': 'ദയവായി OTP നൽകുക',
    'verify_otp': 'OTP പരിശോധിക്കുക',
    'otp_verified': 'OTP വിജയകരമായി പരിശോധിച്ചു',
    'otp_validation_failed': 'OTP പരിശോധന പരാജയപ്പെട്ടു',
    'otp_validation_pending': 'OTP പരിശോധന API ഇതുവരെ ക്രമീകരിച്ചിട്ടില്ല.',
    'alert': 'മുന്നറിയിപ്പ്',
    'success': 'വിജയം',
    'error': 'പിശക്',
    'warning': 'മുന്നറിയിപ്പ്',
    'continue': 'തുടരുക',
    'reset_password_required': 'പാസ്‌വേഡ് മാറ്റണം',
    'reset_password_required_message':
        'തുടരാൻ ദയവായി നിങ്ങളുടെ പാസ്‌വേഡ് മാറ്റുക.',
    'reset_password_title': 'പാസ്‌വേഡ് മാറ്റുക',
    'reset_password_instruction':
        'നിങ്ങളുടെ മർച്ചന്റ് അക്കൗണ്ടിനായി പുതിയ പാസ്‌വേഡ് സൃഷ്ടിക്കുക.',
    'current_password': 'നിലവിലെ പാസ്‌വേഡ്',
    'new_password': 'പുതിയ പാസ്‌വേഡ്',
    'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'current_password_required': 'നിലവിലെ പാസ്‌വേഡ് നൽകുക',
    'new_password_required': 'പുതിയ പാസ്‌വേഡ് നൽകുക',
    'confirm_password_required': 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'passwords_do_not_match': 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല',
    'new_password_same_as_current':
        'പുതിയ പാസ്‌വേഡ് നിലവിലെ പാസ്‌വേഡിൽ നിന്ന് വ്യത്യസ്തമായിരിക്കണം',
    'reset_password_submit': 'പാസ്‌വേഡ് മാറ്റുക',
    'reset_password_success': 'പാസ്‌വേഡ് വിജയകരമായി മാറ്റി',
    'reset_password_failed':
        'പാസ്‌വേഡ് മാറ്റാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    'email_report_sent':
        'റിപ്പോർട്ട് നിങ്ങളുടെ രജിസ്റ്റർ ചെയ്ത ഇമെയിലിലേക്ക് അയച്ചു.',
    'email_report_failed':
        'ഇമെയിൽ റിപ്പോർട്ട് അയക്കാൻ കഴിഞ്ഞില്ല. വീണ്ടും ശ്രമിക്കുക.',
    'no_transactions_to_send': 'അയക്കാൻ ഇടപാടുകൾ ഒന്നുമില്ല.',
    'all_merchants': 'എല്ലാം',
  },
  AppLanguage.tamil: {
    'home': 'முகப்பு',
    'support': 'ஆதரவு',
    'dashboard': 'டாஷ்போர்டு',
    'profile': 'சுயவிவரம்',
    'loading': 'ஏற்றுகிறது...',
    'login_logging_in': 'உள்நுழைகிறது...',
    'login_success': 'உள்நுழைவு வெற்றி!',
    'login_failed': 'உள்நுழைவு தோல்வி',
    'secure_session_unavailable':
        'பாதுகாப்பான அமர்வு சேமிப்பு கிடைக்கவில்லை. HTTPS அல்லது localhost மூலம் செயலியைத் திறந்து மீண்டும் முயற்சிக்கவும்.',
    'unknown_error': 'தெரியாத பிழை',
    'login_subtitle': 'தொடர்வதற்கு முன் உள்நுழையவும்',
    'login_welcome_title': 'மீண்டும் வரவேற்கிறோம்!',
    'login_title': 'மெர்சண்ட் உள்நுழைவு',
    'username_label': 'பயனர்பெயர் / மின்னஞ்சல் / டெர்மினல் ID',
    'username_hint': 'பயனர்பெயர்',
    'username_required': 'பயனர்பெயரை உள்ளிடவும்',
    'password_label': 'கடவுச்சொல்',
    'password_hint': 'கடவுச்சொல்',
    'password_required': 'கடவுச்சொல்லை உள்ளிடவும்',
    'show_password': 'கடவுச்சொல்லைக் காட்டு',
    'hide_password': 'கடவுச்சொல்லை மறை',
    'remember_me': 'என்னை நினைவில் கொள்ளவும்',
    'sign_in': 'உள்நுழை',
    'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'or': '--- அல்லது ---',
    'connect_with_us': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'merchant_name': 'மெர்சண்ட் பெயர்',
    'today_success': 'இன்றைய மொத்த வெற்றிகரமான பரிவர்த்தனைகள்',
    'no_transactions': 'பரிவர்த்தனைகள் இல்லை',
    'no_vpa_transactions': 'VPA பரிவர்த்தனைகள் இல்லை',
    'transactions': 'பரிவர்த்தனைகள்',
    'page': 'பக்கம்',
    'of': 'இல்',
    'previous_page': 'முந்தைய பக்கம்',
    'next_page': 'அடுத்த பக்கம்',
    'view_all_transactions': 'அனைத்து பரிவர்த்தனைகளையும் காண்க',
    'view_all_settlements': 'அனைத்து செட்டில்மென்ட்களையும் காண்க',
    'today_settlements': 'இன்றைய செட்டில்மென்ட்கள்',
    'settled_amount': 'செட்டில் செய்யப்பட்ட தொகை',
    'deductions': 'கழிவுகள்',
    'pending_settlements': 'நிலுவை செட்டில்மென்ட்கள்',
    'total_amount_settled': 'மொத்த செட்டில் தொகை',
    'total_settlements': 'மொத்த செட்டில்மென்ட்கள்',
    'total_transactions': 'மொத்த பரிவர்த்தனைகள்',
    'total_amount': 'மொத்த தொகை',
    'utr_wise_settlement': 'UTR வாரியான செட்டில்மென்ட்',
    'settled_on': 'செட்டில் தேதி',
    'transaction_activity': 'பரிவர்த்தனை செயல்பாடு',
    'settlement_breakdown': 'செட்டில்மென்ட் விவரம்',
    'tap_deduction_details': 'கழிவு விவரங்களை பார்க்க தட்டவும்',
    'hide_deductions': 'கழிவுகளை மறை',
    'view_deductions': 'கழிவுகளை காண்க',
    'amt_packed_settlement': 'செட்டில்மென்டுக்கான தொகை',
    'refund_amount': 'ரீஃபண்ட் தொகை',
    'chargeback_amount': 'சார்ஜ்பேக் தொகை',
    'loan_recovery_amount': 'கடன் மீட்பு தொகை',
    'msf_mdr': 'MSF/MDR',
    'late_stl_fee': 'தாமத செட்டில்மென்ட் கட்டணம்',
    'others': 'மற்றவை',
    'pos_txns_history': 'POS பரிவர்த்தனை வரலாறு',
    'qr_txns_history': 'QR பரிவர்த்தனை வரலாறு',
    'settlements': 'செட்டில்மென்ட்கள்',
    'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
    'dashboard_title': 'டாஷ்போர்டு',
    'dashboard_message': 'டாஷ்போர்டு விவரங்கள் இங்கே காட்டப்படும்.',
    'basic_info': 'அடிப்படை தகவல்',
    'shop_name': 'கடை பெயர்',
    'merchant_id': 'மெர்சண்ட் ID',
    'role': 'பங்கு',
    'device_type': 'சாதன வகை',
    'not_available': 'கிடைக்கவில்லை',
    'no_email': 'மின்னஞ்சல் இல்லை',
    'merchant_user': 'மெர்சண்ட் பயனர்',
    'app_settings': 'ஆப் அமைப்புகள்',
    'app_language': 'ஆப் மொழி',
    'theme': 'தீம்',
    'color_combination': 'நிற கலவை',
    'system': 'சிஸ்டம்',
    'light': 'லைட்',
    'dark': 'டார்க்',
    'about_app': 'ஆப் பற்றி',
    'app_name': 'ஆப் பெயர்',
    'description': 'விளக்கம்',
    'app_description': 'மெர்சண்ட் பேமெண்ட் மற்றும் ஆதரவு ஆப்',
    'quick_actions': 'விரைவு செயல்கள்',
    'loading_options': 'விருப்பங்கள் ஏற்றுகிறது...',
    'select_option': 'ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
    'help_desk': 'ஹெல்ப்\nடெஸ்க்',
    'here_to_help': 'உங்களுக்கு உதவ நாங்கள் உள்ளோம்!',
    'raise_concern': 'உங்கள் பிரச்சினையை தெரிவித்து\nதீர்வு பெறுங்கள்',
    'raising_request': 'கோரிக்கை அனுப்புகிறது...',
    'raise_request': 'கோரிக்கை அனுப்பு',
    'contact_us': 'தொடர்பு கொள்ள:',
    'support_request_success': 'ஆதரவு கோரிக்கை வெற்றிகரமாக அனுப்பப்பட்டது',
    'support_request_failed': 'ஆதரவு கோரிக்கை தோல்வி',
    'filter_required': 'ஃபில்டர் தேவை',
    'select_date_range': 'தேதி வரம்பைத் தேர்ந்தெடுக்கவும்',
    'select_vpa': 'VPA-ஐத் தேர்ந்தெடுக்கவும்',
    'enter_rrn': 'RRN உள்ளிடவும்',
    'enter_app_code': 'ஆப் கோடு உள்ளிடவும்',
    'select_filter_any':
        'தேதி வரம்பு, டெர்மினல், RRN அல்லது ஆப் கோடு தேர்ந்தெடுக்கவும்',
    'ok': 'சரி',
    'reset': 'ரீசெட்',
    'apply': 'பயன்படுத்து',
    'vpa': 'VPA',
    'select': 'தேர்ந்தெடு',
    'payment_tid': 'பேமெண்ட் TID',
    'search_by': 'தேடல்',
    'date': 'தேதி',
    'rrn_app_code': 'RRN/ஆப் கோடு',
    'tid_vpa': 'TID',
    'payment_mode': 'பேமெண்ட் முறை',
    'enter_rrn_hint': 'RRN உள்ளிடவும்',
    'enter_app_code_hint': 'ஆப் கோடு உள்ளிடவும்',
    'today': 'இன்று',
    'yesterday': 'நேற்று',
    'last_7_days': 'கடைசி 7 நாட்கள்',
    'last_1_month': 'கடைசி 1 மாதம்',
    'custom_date_range': 'தனிப்பயன் தேதி வரம்பு',
    'search_result': 'தேடல் முடிவு',
    'select_date': 'தேதி தேர்வு',
    'cancel': 'ரத்து',
    'clear': 'அழி',
    'select_date_range_tooltip': 'தேதி வரம்பைத் தேர்ந்தெடுக்கவும்',
    'back': 'பின்',
    'notifications': 'அறிவிப்புகள்',
    'logout': 'லாக் அவுட்',
    'logout_confirm_title': 'லாக் அவுட் செய்யவா?',
    'logout_confirm_message': 'நீங்கள் லாக் அவுட் செய்ய விரும்புகிறீர்களா?',
    'select_language': 'மொழியை தேர்ந்தெடுக்கவும்',
    'change_language': 'மொழியை மாற்றவும்',
    'download': 'பதிவிறக்கு',
    'send_by_email': 'மின்னஞ்சல் மூலம் அனுப்பு',
    'open_contact_failed': 'இந்த தொடர்பு விருப்பத்தை திறக்க முடியவில்லை',
    'amount': 'தொகை',
    'refresh': 'புதுப்பி',
    'pos_txns_compact': 'POS\nபரிவ.',
    'qr_txns_compact': 'QR\nபரிவ.',
    'settlements_compact': 'செட்டில்\nமெண்ட்',
    'total_amount_settled_today': 'இன்று செட்டில் செய்யப்பட்ட மொத்த தொகை',
    'total_deductions_today': 'இன்றைய மொத்த பிடித்தங்கள்',
    'total_pending_settlements': 'நிலுவையில் உள்ள செட்டில்மெண்ட்கள்',
    'terminals_vpas': 'டெர்மினல்கள் & VPAகள்',
    'terminals': 'டெர்மினல்கள்',
    'vpas': 'VPAகள்',
    'device_application': 'சாதனம் & பயன்பாடு',
    'app_version': 'ஆப் பதிப்பு',
    'os_version': 'OS பதிப்பு',
    'platform': 'பிளாட்ஃபாரம்',
    'device_model': 'சாதன மாடல்',
    'check_for_updates': 'புதுப்பிப்புகளைச் சரிபார்',
    'tap_check_app_updates': 'ஆப் புதுப்பிப்புகளைச் சரிபார்க்க தட்டவும்',
    'app_up_to_date': 'உங்கள் ஆப் புதுப்பிக்கப்பட்டுள்ளது.',
    'app_update_message':
        'புதிய பதிப்பு உள்ளது. தயவுசெய்து ஆப்பை புதுப்பிக்கவும்.',
    'update_required': 'புதுப்பிப்பு அவசியம்',
    'update_available': 'புதுப்பிப்பு உள்ளது',
    'current_version': 'தற்போதைய பதிப்பு',
    'latest_version': 'சமீபத்திய பதிப்பு',
    'later': 'பின்னர்',
    'update': 'புதுப்பி',
    'could_not_open_update_link': 'புதுப்பிப்பு இணைப்பைத் திறக்க முடியவில்லை',
    'no_internet_title': 'இணைய இணைப்பு இல்லை',
    'no_internet_message':
        'உங்கள் இணைப்பைச் சரிபார்க்கவும். இணையம் திரும்பியதும் ஆப் தானாக தொடரும்.',
    'month_vs_transaction_amount': 'மாதம் vs பரிவர்த்தனை தொகை',
    'from': 'இருந்து',
    'to': 'வரை',
    'forgot_password_title': 'கடவுச்சொல் மறந்துவிட்டதா',
    'forgot_password_instruction':
        'கடவுச்சொல் மீட்டமைப்பு உதவிக்கு பயனர்பெயர், மின்னஞ்சல் அல்லது டெர்மினல் ID ஐ உள்ளிடவும்.',
    'forgot_password_identifier_label':
        'பயனர்பெயர் / மின்னஞ்சல் / டெர்மினல் ID',
    'forgot_password_identifier_hint': 'பதிவு செய்யப்பட்ட விவரங்களை உள்ளிடவும்',
    'forgot_password_identifier_required':
        'பயனர்பெயர், மின்னஞ்சல் அல்லது டெர்மினல் ID ஐ உள்ளிடவும்',
    'forgot_password_submit': 'கோரிக்கையை சமர்ப்பி',
    'forgot_password_submitted':
        'கடவுச்சொல் மீட்டமைப்பு கோரிக்கை சமர்ப்பிக்கப்பட்டது',
    'forgot_password_submitted_message':
        'உங்கள் கடவுச்சொல்லை மீட்டமைக்க எங்கள் ஆதரவு குழு உதவும்.',
    'forgot_password_failed':
        'கடவுச்சொல் மீட்டமைப்பு கோரிக்கையை சமர்ப்பிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'otp_sent': 'OTP வெற்றிகரமாக அனுப்பப்பட்டது',
    'otp_validation_title': 'OTP சரிபார்ப்பு',
    'otp_validation_message':
        'உங்கள் பதிவு செய்யப்பட்ட தொடர்புக்கு அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்.',
    'enter_otp': 'OTP ஐ உள்ளிடவும்',
    'otp_required': 'OTP ஐ உள்ளிடவும்',
    'verify_otp': 'OTP சரிபார்',
    'otp_verified': 'OTP வெற்றிகரமாக சரிபார்க்கப்பட்டது',
    'otp_validation_failed': 'OTP சரிபார்ப்பு தோல்வியடைந்தது',
    'otp_validation_pending': 'OTP சரிபார்ப்பு API இன்னும் அமைக்கப்படவில்லை.',
    'alert': 'எச்சரிக்கை',
    'success': 'வெற்றி',
    'error': 'பிழை',
    'warning': 'எச்சரிக்கை',
    'continue': 'தொடரவும்',
    'reset_password_required': 'கடவுச்சொல்லை மாற்ற வேண்டும்',
    'reset_password_required_message': 'தொடர உங்கள் கடவுச்சொல்லை மாற்றவும்.',
    'reset_password_title': 'கடவுச்சொல்லை மாற்று',
    'reset_password_instruction':
        'உங்கள் மெர்சண்ட் கணக்கிற்கு புதிய கடவுச்சொல்லை உருவாக்கவும்.',
    'current_password': 'தற்போதைய கடவுச்சொல்',
    'new_password': 'புதிய கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
    'current_password_required': 'தற்போதைய கடவுச்சொல்லை உள்ளிடவும்',
    'new_password_required': 'புதிய கடவுச்சொல்லை உள்ளிடவும்',
    'confirm_password_required': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'passwords_do_not_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'new_password_same_as_current':
        'புதிய கடவுச்சொல் தற்போதைய கடவுச்சொல்லிலிருந்து வேறுபட்டிருக்க வேண்டும்',
    'reset_password_submit': 'கடவுச்சொல்லை மாற்று',
    'reset_password_success': 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது',
    'reset_password_failed':
        'கடவுச்சொல்லை மாற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'email_report_sent':
        'அறிக்கை உங்கள் பதிவுசெய்யப்பட்ட மின்னஞ்சலுக்கு அனுப்பப்பட்டது.',
    'email_report_failed':
        'மின்னஞ்சல் அறிக்கையை அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'no_transactions_to_send': 'அனுப்ப பரிவர்த்தனைகள் இல்லை.',
    'all_merchants': 'அனைத்தும்',
  },
  AppLanguage.hindi: {
    'home': 'होम',
    'support': 'सपोर्ट',
    'dashboard': 'डैशबोर्ड',
    'profile': 'प्रोफाइल',
    'loading': 'लोड हो रहा है...',
    'login_logging_in': 'लॉगिन हो रहा है...',
    'login_success': 'लॉगिन सफल!',
    'login_failed': 'लॉगिन विफल',
    'secure_session_unavailable':
        'सुरक्षित सत्र संग्रह उपलब्ध नहीं है। ऐप को HTTPS या localhost से खोलकर फिर प्रयास करें।',
    'unknown_error': 'अज्ञात त्रुटि',
    'login_subtitle': 'आगे बढ़ने से पहले साइन इन करें',
    'login_welcome_title': 'वापसी पर स्वागत है!',
    'login_title': 'मर्चेंट साइन इन',
    'username_label': 'यूज़रनेम / ईमेल / टर्मिनल आईडी',
    'username_hint': 'यूज़रनेम',
    'username_required': 'कृपया यूज़रनेम दर्ज करें',
    'password_label': 'पासवर्ड',
    'password_hint': 'पासवर्ड',
    'password_required': 'कृपया पासवर्ड दर्ज करें',
    'show_password': 'पासवर्ड दिखाएं',
    'hide_password': 'पासवर्ड छुपाएं',
    'remember_me': 'मुझे याद रखें',
    'sign_in': 'साइन इन',
    'forgot_password': 'पासवर्ड भूल गए?',
    'or': '--- या ---',
    'connect_with_us': 'हमसे जुड़ें',
    'merchant_name': 'मर्चेंट नाम',
    'today_success': 'आज के कुल सफल लेनदेन',
    'no_transactions': 'कोई लेनदेन उपलब्ध नहीं',
    'no_vpa_transactions': 'कोई वीपीए लेनदेन उपलब्ध नहीं',
    'transactions': 'लेनदेन',
    'page': 'पेज',
    'of': 'में से',
    'previous_page': 'पिछला पेज',
    'next_page': 'अगला पेज',
    'view_all_transactions': 'सभी लेनदेन देखें',
    'view_all_settlements': 'सभी सेटलमेंट देखें',
    'today_settlements': 'आज के सेटलमेंट',
    'settled_amount': 'सेटल्ड राशि',
    'deductions': 'कटौतियां',
    'pending_settlements': 'लंबित सेटलमेंट',
    'total_amount_settled': 'कुल सेटल्ड राशि',
    'total_settlements': 'कुल सेटलमेंट',
    'total_transactions': 'कुल लेनदेन',
    'total_amount': 'कुल राशि',
    'utr_wise_settlement': 'UTR के अनुसार सेटलमेंट',
    'settled_on': 'सेटल्ड ऑन',
    'transaction_activity': 'लेनदेन गतिविधि',
    'settlement_breakdown': 'सेटलमेंट ब्रेकडाउन',
    'tap_deduction_details': 'कटौती विवरण देखने के लिए टैप करें',
    'hide_deductions': 'कटौतियां छिपाएं',
    'view_deductions': 'कटौतियां देखें',
    'amt_packed_settlement': 'सेटलमेंट के लिए पैक राशि',
    'refund_amount': 'रिफंड राशि',
    'chargeback_amount': 'चार्जबैक राशि',
    'loan_recovery_amount': 'लोन रिकवरी राशि',
    'msf_mdr': 'MSF/MDR',
    'late_stl_fee': 'लेट सेटलमेंट शुल्क',
    'others': 'अन्य',
    'pos_txns_history': 'POS लेनदेन इतिहास',
    'qr_txns_history': 'QR लेनदेन इतिहास',
    'settlements': 'सेटलमेंट',
    'recent_transactions': 'हाल के लेनदेन',
    'dashboard_title': 'डैशबोर्ड',
    'dashboard_message': 'डैशबोर्ड विवरण यहां दिखेंगे।',
    'basic_info': 'मूल जानकारी',
    'shop_name': 'दुकान का नाम',
    'merchant_id': 'मर्चेंट आईडी',
    'role': 'भूमिका',
    'device_type': 'डिवाइस प्रकार',
    'not_available': 'उपलब्ध नहीं',
    'no_email': 'ईमेल उपलब्ध नहीं',
    'merchant_user': 'मर्चेंट यूज़र',
    'app_settings': 'ऐप सेटिंग्स',
    'app_language': 'ऐप भाषा',
    'theme': 'थीम',
    'color_combination': 'रंग संयोजन',
    'system': 'सिस्टम',
    'light': 'लाइट',
    'dark': 'डार्क',
    'about_app': 'ऐप के बारे में',
    'app_name': 'ऐप का नाम',
    'description': 'विवरण',
    'app_description': 'मर्चेंट भुगतान और सपोर्ट ऐप',
    'quick_actions': 'त्वरित कार्य',
    'loading_options': 'विकल्प लोड हो रहे हैं...',
    'select_option': 'एक विकल्प चुनें',
    'help_desk': 'हेल्प\nडेस्क',
    'here_to_help': 'हम मदद के लिए यहां हैं!',
    'raise_concern': 'अपनी समस्या बताएं और\nसमाधान पाएं',
    'raising_request': 'रिक्वेस्ट भेजी जा रही है...',
    'raise_request': 'रिक्वेस्ट भेजें',
    'contact_us': 'संपर्क करें:',
    'support_request_success': 'सपोर्ट रिक्वेस्ट सफलतापूर्वक भेजी गई',
    'support_request_failed': 'सपोर्ट रिक्वेस्ट विफल',
    'filter_required': 'फिल्टर आवश्यक है',
    'select_date_range': 'कृपया तारीख सीमा चुनें',
    'select_vpa': 'कृपया वीपीए चुनें',
    'enter_rrn': 'कृपया RRN दर्ज करें',
    'enter_app_code': 'कृपया ऐप कोड दर्ज करें',
    'select_filter_any': 'कृपया तारीख सीमा, टर्मिनल, RRN या ऐप कोड चुनें',
    'ok': 'ठीक है',
    'reset': 'रीसेट',
    'apply': 'लागू करें',
    'vpa': 'वीपीए',
    'select': 'चुनें',
    'payment_tid': 'पेमेंट TID',
    'search_by': 'इसके द्वारा खोजें',
    'date': 'तारीख',
    'rrn_app_code': 'RRN/ऐप कोड',
    'tid_vpa': 'TID',
    'payment_mode': 'भुगतान मोड',
    'enter_rrn_hint': 'RRN दर्ज करें',
    'enter_app_code_hint': 'ऐप कोड दर्ज करें',
    'today': 'आज',
    'yesterday': 'कल',
    'last_7_days': 'पिछले 7 दिन',
    'last_1_month': 'पिछला 1 महीना',
    'custom_date_range': 'कस्टम तारीख सीमा',
    'search_result': 'खोज परिणाम',
    'select_date': 'तारीख चुनें',
    'cancel': 'रद्द करें',
    'clear': 'साफ करें',
    'select_date_range_tooltip': 'तारीख सीमा चुनें',
    'back': 'वापस',
    'notifications': 'सूचनाएं',
    'logout': 'लॉग आउट',
    'logout_confirm_title': 'लॉग आउट करें?',
    'logout_confirm_message': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'select_language': 'भाषा चुनें',
    'change_language': 'भाषा बदलें',
    'download': 'डाउनलोड',
    'send_by_email': 'ईमेल से भेजें',
    'open_contact_failed': 'यह संपर्क विकल्प नहीं खुल सका',
    'amount': 'राशि',
    'refresh': 'रिफ्रेश',
    'pos_txns_compact': 'POS\nलेनदेन',
    'qr_txns_compact': 'QR\nलेनदेन',
    'settlements_compact': 'सेटल\nमेंट',
    'total_amount_settled_today': 'आज सेटल की गई कुल राशि',
    'total_deductions_today': 'आज की कुल कटौतियां',
    'total_pending_settlements': 'कुल लंबित सेटलमेंट',
    'terminals_vpas': 'टर्मिनल और VPA',
    'terminals': 'टर्मिनल',
    'vpas': 'VPA',
    'device_application': 'डिवाइस और ऐप्लिकेशन',
    'app_version': 'ऐप संस्करण',
    'os_version': 'OS संस्करण',
    'platform': 'प्लेटफॉर्म',
    'device_model': 'डिवाइस मॉडल',
    'check_for_updates': 'अपडेट जांचें',
    'tap_check_app_updates': 'ऐप अपडेट जांचने के लिए टैप करें',
    'app_up_to_date': 'आपका ऐप अपडेट है.',
    'app_update_message': 'नया संस्करण उपलब्ध है. कृपया ऐप्लिकेशन अपडेट करें.',
    'update_required': 'अपडेट आवश्यक',
    'update_available': 'अपडेट उपलब्ध',
    'current_version': 'वर्तमान संस्करण',
    'latest_version': 'नवीनतम संस्करण',
    'later': 'बाद में',
    'update': 'अपडेट',
    'could_not_open_update_link': 'अपडेट लिंक नहीं खुल सका',
    'no_internet_title': 'इंटरनेट कनेक्शन नहीं है',
    'no_internet_message':
        'कृपया अपना कनेक्शन जांचें. इंटरनेट वापस आने पर ऐप अपने आप चालू हो जाएगा.',
    'month_vs_transaction_amount': 'महीना vs लेनदेन राशि',
    'from': 'से',
    'to': 'तक',
    'forgot_password_title': 'पासवर्ड भूल गए',
    'forgot_password_instruction':
        'पासवर्ड रीसेट सहायता के लिए अपना यूज़रनेम, ईमेल या टर्मिनल ID दर्ज करें.',
    'forgot_password_identifier_label': 'यूज़रनेम / ईमेल / टर्मिनल ID',
    'forgot_password_identifier_hint': 'रजिस्टर्ड विवरण दर्ज करें',
    'forgot_password_identifier_required':
        'कृपया यूज़रनेम, ईमेल या टर्मिनल ID दर्ज करें',
    'forgot_password_submit': 'रिक्वेस्ट सबमिट करें',
    'forgot_password_submitted': 'पासवर्ड रीसेट रिक्वेस्ट सबमिट की गई',
    'forgot_password_submitted_message':
        'हमारी सपोर्ट टीम आपका पासवर्ड रीसेट करने में मदद करेगी.',
    'forgot_password_failed':
        'पासवर्ड रीसेट रिक्वेस्ट सबमिट नहीं हो सकी. कृपया फिर कोशिश करें.',
    'otp_sent': 'OTP सफलतापूर्वक भेजा गया',
    'otp_validation_title': 'OTP सत्यापन',
    'otp_validation_message':
        'अपने रजिस्टर्ड संपर्क पर भेजा गया OTP दर्ज करें.',
    'enter_otp': 'OTP दर्ज करें',
    'otp_required': 'कृपया OTP दर्ज करें',
    'verify_otp': 'OTP सत्यापित करें',
    'otp_verified': 'OTP सफलतापूर्वक सत्यापित हुआ',
    'otp_validation_failed': 'OTP सत्यापन विफल रहा',
    'otp_validation_pending': 'OTP सत्यापन API अभी कॉन्फ़िगर नहीं है.',
    'alert': 'अलर्ट',
    'success': 'सफलता',
    'error': 'त्रुटि',
    'warning': 'चेतावनी',
    'continue': 'जारी रखें',
    'reset_password_required': 'पासवर्ड बदलना आवश्यक है',
    'reset_password_required_message':
        'जारी रखने के लिए कृपया अपना पासवर्ड बदलें.',
    'reset_password_title': 'पासवर्ड बदलें',
    'reset_password_instruction': 'अपने मर्चेंट खाते के लिए नया पासवर्ड बनाएं.',
    'current_password': 'वर्तमान पासवर्ड',
    'new_password': 'नया पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'current_password_required': 'कृपया वर्तमान पासवर्ड दर्ज करें',
    'new_password_required': 'कृपया नया पासवर्ड दर्ज करें',
    'confirm_password_required': 'कृपया नए पासवर्ड की पुष्टि करें',
    'passwords_do_not_match': 'पासवर्ड मेल नहीं खाते',
    'new_password_same_as_current':
        'नया पासवर्ड वर्तमान पासवर्ड से अलग होना चाहिए',
    'reset_password_submit': 'पासवर्ड बदलें',
    'reset_password_success': 'पासवर्ड सफलतापूर्वक बदल गया',
    'reset_password_failed': 'पासवर्ड बदलने में विफल. कृपया फिर प्रयास करें.',
    'email_report_sent': 'रिपोर्ट आपके पंजीकृत ईमेल पर भेज दी गई है.',
    'email_report_failed':
        'ईमेल रिपोर्ट भेजी नहीं जा सकी. कृपया फिर प्रयास करें.',
    'no_transactions_to_send': 'भेजने के लिए कोई लेनदेन उपलब्ध नहीं है.',
    'all_merchants': 'सभी',
  },
};
